FROM ghcr.io/renovatebot/renovate

USER 0
RUN apt update && apt install -y gettext

# https://github.com/renovatebot/renovate/blob/main/tools/docker/Dockerfile
USER 12021
WORKDIR /usr/src/app
ENTRYPOINT ["/usr/local/sbin/renovate-entrypoint.sh"]
CMD ["renovate"]
